[parity]
chain = "./spec/spec.json"
base_path = "parity-data/node0"
no_persistent_txqueue = true

[ui]
disable = true

[network]
port = 30300
discovery = true
nat = "none"
interface = "local"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces", "rpc", "shh", "shh_pubsub"]
port = 8540

[mining]
min_gas_price = 1000000000
reseal_min_period = 0
hbbft_public_key_set = "{\"commit\":{\"coeff\":[[137,86,13,240,132,222,45,26,109,192,31,128,39,38,36,170,172,130,22,82,184,97,175,251,71,106,228,110,119,50,32,0,112,133,66,46,233,29,228,238,94,233,161,93,82,244,169,64]]}}"

[websockets]
port = 9540

[ipc]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false

[misc]
#logging = "engine=trace,miner=trace,reward=trace"
