[parity]
chain = "pos-contracts/spec.json"
base_path = "parity-data/node3"

[ui]
disable = true

[network]
id = 101
port = 30303
reserved_peers="parity-data/reserved-peers"
reserved_only = true
min_peers = 3
interface = "127.0.0.1"
discovery = true

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
port = 8543

[websockets]
port = 9543

[ipc]
disable = false

[secretstore]
disable = true

[ipfs]
enable = false

[account]
unlock = ["0x522df396ae70a058bd69778408630fdb023389b2"]
password = ["config/password"]

[mining]
force_sealing = true
# min_gas_price = 1000000000
engine_signer = "0x522df396ae70a058bd69778408630fdb023389b2"
reseal_on_txs = "none"
extra_data = "Parity"

[misc]
logging = "engine=trace,miner=trace"
